// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmunsoqxqgendtumrfjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtdW5zb3F4cWdlbmR0dW1yZmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NjcwNDcsImV4cCI6MjA1NjM0MzA0N30.b7jGFFfyi9BX8zbQtWX_Aq-W0jvcmLJyyWNQ_2PlSGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);